'use strict';

const { Router } = require('express');
const db = require('../db');
const { getKey } = require('./config');
const { buildPrompt, SYSTEM_PROMPT } = require('../agent/prompt');
const { streamDiagnosis } = require('../agent/claude');
const { createPR } = require('../agent/github');

const router = Router();

// POST /sessions/:id/diagnose — SSE stream of Claude diagnosis
router.post('/:id/diagnose', async (req, res) => {
  const session = db.sessions.get.get(req.params.id);
  if (!session) return res.status(404).json({ error: 'Session not found' });

  const apiKey = getKey('anthropic_key');
  if (!apiKey) return res.status(400).json({ error: 'Anthropic API key not configured. POST /config first.' });

  const ev = db.evidence.get.get(req.params.id);
  if (!ev) return res.status(400).json({ error: 'No evidence stored for this session' });

  // SSE headers
  res.setHeader('Content-Type', 'text/event-stream');
  res.setHeader('Cache-Control', 'no-cache');
  res.setHeader('Connection', 'keep-alive');
  res.flushHeaders();

  const send = (obj) => res.write(`data: ${JSON.stringify(obj)}\n\n`);

  const evidence = {
    calmCtx:  ev.calm_ctx ? JSON.parse(ev.calm_ctx) : null,
    logs:     ev.logs,
    logsNote: ev.logs_note,
    commits:  JSON.parse(ev.commits),
  };

  const sourceFiles = require('../evidence').readServiceFiles(session.node_id);
  const userMessage = buildPrompt(evidence, sourceFiles);
  db.messages.insert.run(req.params.id, 'user', userMessage);

  let fullText = '';
  let diagnosis = null;

  try {
    await streamDiagnosis(apiKey, SYSTEM_PROMPT, userMessage, (evt) => {
      if (evt.type === 'text') {
        fullText += evt.text;
        send({ type: 'text', text: evt.text });
      } else if (evt.type === 'diagnosis') {
        diagnosis = evt.result;
        send({ type: 'diagnosis', result: evt.result });
      } else if (evt.type === 'done') {
        send({ type: 'done' });
      } else if (evt.type === 'error') {
        send({ type: 'error', message: evt.message });
      }
    });
  } catch (err) {
    send({ type: 'error', message: err.message });
  }

  // Persist assistant response
  const assistantContent = diagnosis
    ? JSON.stringify(diagnosis)
    : fullText;
  db.messages.insert.run(req.params.id, 'assistant', assistantContent);

  if (diagnosis) {
    db.sessions.updateStatus.run('diagnosed', req.params.id);
  }

  res.end();
});

// POST /sessions/:id/pr — create GitHub PR from stored diagnosis
router.post('/:id/pr', async (req, res) => {
  const session = db.sessions.get.get(req.params.id);
  if (!session) return res.status(404).json({ error: 'Session not found' });

  const pat       = getKey('github_pat');
  const ghRepo    = getKey('github_repo'); // "owner/repo"
  if (!pat || !ghRepo) return res.status(400).json({ error: 'GitHub PAT and repo not configured. POST /config first.' });

  const { filePath, fixedContent, rootCause, explanation } = req.body ?? {};
  if (!filePath || !fixedContent) return res.status(400).json({ error: 'filePath and fixedContent required' });

  const [owner, repo] = ghRepo.split('/');
  const branchName = `fix/${session.node_id}-${session.id.slice(0, 8)}`;
  const prTitle = `fix(${session.node_id}): ${explanation ?? 'incident fix'}`;
  const prBody = [
    `## Incident Fix`,
    ``,
    `**Affected service:** ${session.node_name}`,
    `**Root cause:** ${rootCause ?? '(see diagnosis)'}`,
    ``,
    `**Explanation:** ${explanation ?? ''}`,
    ``,
    `---`,
    `*Generated by Codebase Visualizer incident agent*`,
    `*Session: ${session.id}*`,
  ].join('\n');

  try {
    const result = await createPR({ pat, owner, repo, filePath, fixedContent, branchName, prTitle, prBody });
    db.prs.insert.run(session.id, result.prUrl, result.branch, filePath);
    db.sessions.updateStatus.run('pr_created', session.id);
    res.json(result);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

module.exports = router;
